### ISSUE TITLE
Filter draft post on production build

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#111]
I would love to have an options in markdown file for draft. Like this ?

```

---
title: "foo"
draft: true

---
```

And that page won't appear on production build.

**Comment by MoOx** [comment]
I think the issue here (if you can confirm) is to "hide" the post in post listing + does not create file.

A way to handle that currently is "just" to hide from post listing, using a filter depending on the env. But file will still be emitted.
Maybe we can add a plugin know we have this. This might require a change in the loader to prevent loader emitting the file.

**Comment by thangngoc89** [comment]
I mentioned this before https://github.com/MoOx/phenomic/issues/630#issuecomment-240528812

**Comment by MoOx** [comment]
Yeah but my other issue was more about a real plugin system, not just related to the loader :)
Anyway we know what we need to do!

**Comment by thangngoc89** [comment]
ok. Sounds good to me

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
Fixed in master
