### ISSUE TITLE
Easily generate pages per metadata

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#15]
Eg: 

- tags
- date (year, year/month...)

with a way to sort / paginate results

**Comment by thangngoc89** [comment]
[Dynamic routing mind help](https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md)

Add a `NotFound` route. Don't use `*` to catch all route.

**Comment by MoOx** [comment]
For this, we will have indeed to really use react-router. But I think * will be a requirement since we don't know (when writing routes) what pages you will have.

**Comment by thangngoc89** [comment]
We do. After md-collection-loader finishes, we know all the routes available. User `web_modules/src/routes.js` should be a small slice of routes. Statinamic will control the others

**Comment by MoOx** [comment]
> Statinamic will control the others

That's why there is a *.

**Comment by thangngoc89** [comment]
Yeah. sorry :)

**Comment by MoOx** [comment]
And * is the recommended way to catch all routes (and so not found).
Not found is kind of our PageContainer || PageError.

**Comment by thangngoc89** [comment]
I'll take a look at this later. Really want a tags system

**Comment by MoOx** [comment]
I will work on it after introducing search in the default boilerplate

The idea is to use routes with names like "tag/:tags", read routes to find ":tags" and generate pages based on all metadata "tags".

Something like that. This way user will be able to control url generations.

**Comment by MoOx** [comment]
It's a requirement for me too :)

**Comment by thangngoc89** [comment]
Sound easy. Haha. How about I work on search and you work on this. Adding search is much easier.

**Comment by MoOx** [comment]
Let's do this.

**Comment by thangngoc89** [comment]
I have a upcoming project that needs a static site generator. Tagging system is a requirement so I did a little research for making such a system for Statinamic.

And here is the result : https://github.com/thangngoc89/blog/pull/89 
Nothing fancy there. It stills a proof of concept, need a lot of tests and a patch in statinamic core to make it work. I'll walk you through the process:

- Hook a callback to webpack's compiler done event
- Get tags list from `statinamic/lib/content-loader/cache.js`
- With each tags, push a new object to `cache.js` 

```
cache.push({
  __url: `/tags/${item}`,
   __resourceUrl: `/tags/${item}/index.html`
})
```

- Catch this routes in React Router (`tags/:tag`)
- Make a new Component to show posts with current tags in React Router
- That's it for static build. To make it work for dev mode, I need to make reading dataUrl optional

Wrap these LoC in a condition (check for availability of `item.__dataUrl`)
https://github.com/MoOx/statinamic/blob/81baba84c5b8a49564ef8b2c82996148bf8f02ed/src/builder/server.js#L155-L165


Probably 404 page will be benefit from this patch too. No need for download data file for such a page.

But there is some issues to solve:

- How to inject tag data to Tag Component (to be safe, you'll will have to slugify the tag, we need to inject the original tag to the Component since slugify every tag we found is costly and make the js bundle bigger)
- The Webpack plugin is ugly, we probably need to provide a clean API for this.

**Comment by MoOx** [comment]
I will work on this after 0.9 (I was supposed to but, life and shit...).

I want this to be really simple. A route and a layout/component should be enough. I think we need to use something like [redial]() to have a universal way to fetch data so we can use a component during build or on client runtime (currently for pages, there is 2 pieces of code to get data, one for static and one for client, which kind of sucks).

**Comment by thangngoc89** [comment]
>  life and shit...

Don't worry, you're doing a really good job.

> A route and a layout/component should be enough

:+1: I love simple

**Comment by thangngoc89** [comment]
[async-props](https://github.com/ryanflorence/async-props) is another option. It's from react-router creator. and it's uses react-router middleware

**Comment by MoOx** [comment]
I am on it. Should not take that long and user API will be straight forward (nothing specific, just routes with parameters that match name in the frontmatter and boom, generation).

**Comment by MoOx** [comment]
This is implemented in 0.16 🎉

**Comment by blairanderson** [comment]
@MoOx do you have a link to the source on this? i cannot find documentation

**Comment by MoOx** [comment]
See https://phenomic.io/docs/usage/routing/#uses-react-router-routes-parameters-to-create-dynamic-pages
