### ISSUE TITLE
Plugins for collection-loader

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#260]
# How will it work ?

Mutate `textData` (need a better name) directly to add/ remove fields of json files programtically . If return null, don't emit this file or add it to collection.

# Default public plugins

Put them in  ( `statinamic/lib/content-loader/plugins/*`) 

- Markdown renderer
- Description renderer #251 
- Don't build draft post on production #111 

Some ideas for plugin:

- Others renderer with description renderer as well (ASCIIDoc, ...)

# Backlog 

Adding new files to collection should be easy (for tagging,...)

**Comment by DavidWells** [comment]
👍

**Comment by MoOx** [comment]
I will make something simple:
a content-loader plugin will be (pageData) => pageData. So it must returns a new pageData object (pageData will be { head: { ... }, body: { .. })... The only requirement will be a head, but I am not even sure it should be a requirement. A pageData should be anything the user want.
I will implement something simple with the following plugins:
- add-head-property-from-config (default head value from content-loader config)
- add-head-from-content (default behavior, but moved as a plugin)
- add-head.description-property-from-md-content (see #251)
- add-body-property-from-md-content (renderer method)
- add-raw-property-from-content (see #189)
- add-rawBody-property-from-content (see #189)

By default I think we should add all except raw & rawBody plugins.

Not sure about the naming, we might think about this a bit more. Since plugins can do anything (add/remove) should we prefix? Also since it can use content or not (eg: config) we might specify this too? I think mentionning the type (-md) can be a good idea too.

Any thoughts?

I am also thinking about passing collection as an argument, will check if it's possible (so a plugin can affect the entire collection à la metalsmith - the problem is that plugins will be called for each file, contrary to metalsmith which call a plugin once per build... so not sure if that a good thing - we might prefer collection plugins - maybe we should have "pagePlugins" and "collectionPlugin").

**Comment by thangngoc89** [comment]
The naming convention looks good to me. But I have 1 concern, do we need all of those plugins ? Isn't gray-matter provides all the information we need ?

**Comment by MoOx** [comment]
`gray-matter` only handle the head, so it will only be used in `add-head-from-content`.

**Comment by MoOx** [comment]
My wip is almost ready. Will make a PR soon
