### ISSUE TITLE
Consider restricting css modules to `sources` and making CSS Modules not the default way to style

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#516]
For now the webpack rules for CSS can leads to bugs (even if nobody reported some ;) ) or cause issue with CSS consumed from node_modules (since there is no `include`  for CSS atm), cause most CSS from npm (even if there is not a lot) is probably global CSS.

So here is my idea(s):
- making global css default for .css files, and making css module for .module.css or .m.css or any other convention
- keeping CSS modules for .css but restrict to web_modules + .global.css in web_modules + global CSS from all CSS from node_modules (but this can leads to bugs to, if, let's say, a react component in your node_modules need CSS modules.
- making global CSS default, and remove CSS Modules from the default boilerplate

Not sure what people wants. I see that gatsbyjs is pretty popular and have low standards (just global css by default and they plan to add .module.css for CSS Modules).

Any thoughts?

**Obviously this can be adjust by the user (due to where it's configured) and won't create a breaking change as it will affect new setup only.**

**Comment by MoOx** [comment]
For now I updated the default boilerplate to scope the default behavior (CSS Modules + *.global.css files) to web_modules folder while we decide for something better (if we can), but the discussion is just starting ;)

**Comment by facelesspanda** [comment]
Here's a personal opinion from a newcomer (both to Phenomic and modern front-end development):

I don't get CSS modules. I don't understand if they each create a new CSS file, or if they're in the end bundled up in a single file but with class names that are somehow modified to some unique-to-a-module value. I guess the latter, because creating multiple files would mean multiple fetch requests, thus extra network congestion.

But I don't get the point of having classes unique to a component or something. The basic idea of CSS originally was to have generic styling rules that would apply to the whole doc so that authoring structured it, and layouting that structure, was two separate processes and concerns. With class names that only apply to a component or two, though, I don't understand how it's different than styling from the layout.
CSS Modules allow reuse of those small bits of rules, I guess, so there's the difference, but if you're gonna reuse rules, why not having them apply globally anyway and just use smart class names that bind the structure semantic to the styling rules and intelligent selectors to style what you want to style. Having specific rules for components that call such or such css module, to me, is a basically creating very specific selectors, or very specific class names, each are possible with global css, and you don't break consistency.

So I don't know, I'm inclined to prefer the global-first approach, simply because most of the time you're gonna have modular Sass, modular React components, and (in my opinion), should keep those two workflows separate, with upstream decisions on what semantic is gonna be layouted. (If your site need cards of some sort, decide together on a class name, and everyone uses that.)
The CSS Module use-case, at least to me, seems like a very uncommon one: most of the modularity of UI can be achieved with simply smarting through CSS dev. So if it should be kept, I would personally prefer marking it in the name like `*.mod.css`

That's a vote for global-first. ✋

**Comment by DavidWells** [comment]
Check out this slide deck and the videos in the description https://speakerdeck.com/davidwells/bulletproof-css-in-react for more information on postcss, CSS modules and why they are super rad.

Global CSS has its place but local has a lot of benefits.

The two work very well together :)

That said you can write all of your CSS in phenomic with global styles in the *.global.css files. Phenomic is very flexible for you

**Comment by MoOx** [comment]
You can also just remove the webpack section that handle this, and use global without the weird extension :)

**Comment by bloodyowl** [comment]
Going to be fixed with #925 (not going to handle this)

**Comment by MoOx** [comment]
No more css assumption by phenomic in v1.
