### ISSUE TITLE
Does not work correctly using Windows/PowerShell

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#865]
Following this https://github.com/MoOx/phenomic/issues/589#issuecomment-242885411

**Comment by akfish** [comment]
As mentioned in #589, this issue seems to be related to webpack/webpack#2362. The latter issue suggests that nodejs on windows handles drive letters in paths inconsistently, webpack considers `f:\foo` and `F:\foo` 2 different paths. Those two behavior together causes this issue.

To make things weirder, additional tests I just did suggests that phenomic works in `cmd.exe` regardless of the capitalization of the drive letter. So something else is going on with PowerShell's environment.

Maybe we could just wait for webpack or node.js to address this issue and see if this problem will go away?

**Comment by MoOx** [comment]
Probably :)

**Comment by MoOx** [comment]
Will check that later with v1.
