### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by Maxhodges** [MoOx/phenomic#939]
I see a gazillion unterminated statements in the javaScript when I pull this project. Is someone on the team officially against terminating statements with semicolons? It's widely considered a best practice for JavaScript. I'm considering fixing them all in a pull-request, but wanted to ask first in case someone prefers this style for some reason (i.e. my pull-request will be rejected.)

**Comment by Maxhodges** [comment]
example: unterminated statements marked with //<--

All of these statements can end with a ; but none of them must. Some consider it a good habit to terminate each statement with a ; – that makes your code a little easier to parse, and to compress: **if you remove line breaks you needn’t worry about several statements ending up unseparated on the same line.**

```javascript
phenomicClient({ metadata, routes, store }) //<--

// md files processed via phenomic-loader to JSON & generate collection
let mdContext = require.context("../content", true, /\.(md|markdown)$/) //<--
mdContext.keys().forEach(mdContext) //<--

// hot loading
if (module.hot) {

  // hot load md
  module.hot.accept(mdContext.id, () => {
    mdContext = require.context("../content", true, /\.(md|markdown)$/) //<--
    const mdHotUpdater = require("phenomic/lib/client/hot-md").default //<--
    const requireUpdate = mdHotUpdater(mdContext, window.__COLLECTION__, store) //<--
    mdContext.keys().forEach(requireUpdate) //<--
  })//<--
```

**Comment by MoOx** [comment]
I personally don't see any value added for semicolons (and about the [few edges cases](https://github.com/feross/standard/blob/master/RULES.md#semicolons) that might create issues, I prefer to have just 2 or 3 semicolons than the opposite - but actually, I am never facing this issues in the real world).

- Contributors are not bothered by this and can type semicolons. eslint will automatically remove useless semicolons and will only keep the necessary ones.
- [standard js](https://github.com/feross/standard), a widely used project, don't recommend semicolons
- You can probably use eslint --fix to "fix" the default theme as soon as you use it. We might add an option during the setup if that can make some people happy to handle the "pain" :)

I am the main contributor as the graph will show you that why the codebase don't have those.

But [it's](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) [fine.](http://inimino.org/~inimino/blog/javascript_semicolons) [Really!](https://www.youtube.com/watch?v=gsfbh17Ax9I)

I would be really happy to do some bikeshedding if the project didn't have so many issues open and a major release on its way, but honestly, my time is very limited as the moment.
I am pretty sure, since this won't add any value, we can stop discuss about this for now :)
